### ISSUE TITLE
Add JavaScript projects

### ISSUE THREAD

**Issue by i-aka5h** [i-aka5h/Hack-October#1]

**Comment by Sougata2** [comment]
Can I contribute to this ?

**Comment by atharvai812** [comment]
Assign me

**Comment by i-aka5h** [comment]
@Sougata2 @atharvai812 yes you can, make sure your projects are unique.

**Comment by vavy06** [comment]
Hey! I would like to add my project as well. Please assign to me.

**Comment by i-aka5h** [comment]
@vavy06 assigned. Make sure your project is different and unique.

**Comment by mohithgupta** [comment]
I would to add projects (that are not already present), Also can I add python programs? Or do I have to create a new issue for that?

**Comment by i-aka5h** [comment]
Go ahead and for python you can create a new issue, I will assign you.
