### ISSUE TITLE
Merge Intervals - Python

### ISSUE THREAD

**Issue by aditim26** [i-aka5h/Hack-October#135]
Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.

Examples:
![image](https://user-images.githubusercontent.com/91279248/197267585-47a08e76-445c-48e8-b7b2-31f301865e99.png)

**Comment by aditim26** [comment]
Please Assign me this issue

**Comment by i-aka5h** [comment]
@aditim26 We are not accepting DSA programs, this is strictly against the values of hacktoberfest. There are many open issues, give them a try :)
