### ISSUE TITLE
Count Down Timer

### ISSUE THREAD

**Issue by aditim26** [i-aka5h/Hack-October#148]
In this Project, the user will enter the time in seconds and after the specified amount of time Terminal will show a Time Out.

**Comment by aditim26** [comment]
Please assign me this issue

**Comment by acash1809** [comment]
@aditim26 pls find other repos as well because you are making all your 4 PRs eadily accepted using minir issues. So we will not be accepting anymore issues from your side. You can see other issues in this repo if you want to work honestly. Goodluck

**Comment by acash1809** [comment]
Btw in which year in abes?
