### ISSUE TITLE
Make an about us page and add contributors name

### ISSUE THREAD

**Issue by acash1809** [i-aka5h/Hack-October#32]
Make an about us page using html, CSS and javascript.
Link the repository and add names of contributors in it.

Make sure to add a new folder with name {About us page}/{html file}

####  To get your PR accepted-
-  Star this repository
-  Get assigned first
-  Follow proper instructions

**Comment by Divjyo15** [comment]
Hello @acash1809 what type of about us page?

**Comment by acash1809** [comment]
@Divjyo15  make a simple aboutus.html and use some CSS to design it if you can add javascript its good if you dont want to then its okay make sure to add contributors name in page.
Any relevant design will work

**Comment by acash1809** [comment]
@Divjyo15 let me know if you want to work on this

**Comment by Divjyo15** [comment]
@acash1809 yeah, you can assign me. May I know if the page is for a portfolio or anything else?

**Comment by acash1809** [comment]
@Divjyo15 the page is an example which contains info of github repo and contributors name but you just need to do what i said above, rest of the work ill let other beginners to do
Assigning you

**Comment by vader22a** [comment]
What all details do we have to mention in this about us page.

**Comment by vader22a** [comment]
Contributors as in?

**Comment by i-aka5h** [comment]
It'd be fine if you can do static.

**Comment by vader22a** [comment]
pls assign me then

**Comment by i-aka5h** [comment]
@vader22a assigned.

**Comment by acash1809** [comment]
@vader22a you can make /AboutUsPage/  folder name in Hack-October and add your project there.
Only contributors name and link of this repo is enough for now
