### ISSUE TITLE
I want to contribute one more file "Contribute.md" which contains all the steps for how to clone, merge, create issue, pull request for a project 

### ISSUE THREAD

**Issue by dhawal-793** [i-aka5h/Hack-October#52]

**Comment by i-aka5h** [comment]
@dhawal-793 That would be great.

**Comment by dhawal-793** [comment]
Can you add the hacktoberfest-accepted label to this issue as the file is already merged

**Comment by dhawal-793** [comment]
> @dhawal-793 That would be great.

@i-aka5h Can you add the hacktoberfest-accepted label to this issue as the file is already merged
