### ISSUE TITLE
I want to add stopwatch in java using android studio

### ISSUE THREAD

**Issue by akshmangal005** [i-aka5h/Hack-October#6]
Please assign me this issue.

**Comment by i-aka5h** [comment]
Assigned @akshmangal005 . Make sure to create a new folder for android studio.

**Comment by SanjaySargam** [comment]
I want to work on this issue. Please kindly assign me?

**Comment by i-aka5h** [comment]
@SanjaySargam please create a new issue for the same, I'll assign you.
